export const EXERCISE_ALIASES = [
  ["bb bench", "barbell bench press"],
  ["bench", "barbell bench press"],
  ["bench press", "barbell bench press"],
  ["inc bench", "barbell incline bench press"],
  ["incline bench", "barbell incline bench press"],
  ["incline db press", "dumbbell incline bench press"],
  ["inc db press", "dumbbell incline bench press"],
  ["db incline press", "dumbbell incline bench press"],
  ["db press", "dumbbell bench press"],
  ["dumbbell press", "dumbbell bench press"],
  ["chest press", "lever chest press"],
  ["pec deck", "lever pec deck fly"],
  ["fly", "dumbbell fly"],
  ["db fly", "dumbbell fly"],
  ["cable fly", "cable standing fly"],
  ["lat pulldown", "cable lat pulldown full range of motion"],
  ["lpd", "cable lat pulldown full range of motion"],
  ["pull down", "cable lat pulldown full range of motion"],
  ["pulldown", "cable lat pulldown full range of motion"],
  ["pullup", "pull-up"],
  ["pull up", "pull-up"],
  ["chinup", "chin-up"],
  ["chin up", "chin-up"],
  ["row", "barbell bent over row"],
  ["bb row", "barbell bent over row"],
  ["barbell row", "barbell bent over row"],
  ["db row", "dumbbell row"],
  ["dumbbell row", "dumbbell row"],
  ["machine row", "lever seated row"],
  ["cable row", "cable seated row"],
  ["seated row", "cable seated row"],
  ["chest supported row", "dumbbell incline row"],
  ["rear delt", "cable rear delt row"],
  ["rear delt fly", "cable rear delt fly"],
  ["squat", "barbell full squat"],
  ["bb squat", "barbell full squat"],
  ["leg press", "lever leg press"],
  ["leg ext", "lever leg extension"],
  ["leg extension", "lever leg extension"],
  ["leg curl", "lever lying leg curl"],
  ["seated leg curl", "lever seated leg curl"],
  ["lying leg curl", "lever lying leg curl"],
  ["lunge", "dumbbell lunge"],
  ["weighted lunge", "dumbbell lunge"],
  ["split squat", "dumbbell split squat"],
  ["deadlift", "barbell deadlift"],
  ["rdl", "barbell romanian deadlift"],
  ["romanian deadlift", "barbell romanian deadlift"],
  ["hip thrust", "barbell hip thrust"],
  ["glute bridge", "barbell glute bridge"],
  ["calf", "lever seated calf raise"],
  ["calf raise", "lever seated calf raise"],
  ["shoulder press", "dumbbell shoulder press"],
  ["db shoulder press", "dumbbell shoulder press"],
  ["ohp", "barbell standing overhead press"],
  ["overhead press", "barbell standing overhead press"],
  ["arnold press", "dumbbell arnold press"],
  ["lateral raise", "dumbbell lateral raise"],
  ["lat raise", "dumbbell lateral raise"],
  ["side raise", "dumbbell lateral raise"],
  ["front raise", "dumbbell front raise"],
  ["upright row", "barbell upright row"],
  ["curl", "dumbbell bicep curl"],
  ["db curl", "dumbbell bicep curl"],
  ["dumbbell curl", "dumbbell bicep curl"],
  ["barbell curl", "barbell curl"],
  ["ez curl", "ez barbell curl"],
  ["z-bar curl", "ez barbell curl"],
  ["scott curl", "dumbbell preacher curl"],
  ["preacher curl", "dumbbell preacher curl"],
  ["hammer curl", "dumbbell hammer curl"],
  ["pushdown", "cable triceps pushdown"],
  ["push down", "cable triceps pushdown"],
  ["triceps pushdown", "cable triceps pushdown"],
  ["tri pushdown", "cable triceps pushdown"],
  ["kickback", "dumbbell kickback"],
  ["skullcrusher", "ez barbell lying triceps extension"],
  ["skull crusher", "ez barbell lying triceps extension"],
  ["plank", "front plank"],
  ["crunch", "crunch"],
  ["leg raise", "lying leg raise"]
];
